apiVersion: v1
kind: Secret
metadata:
  name: {{ template "postgresql.fullname" . }}
  labels:
    chart: {{ template "postgresql.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
{{- if .Values.global.postgresql.extraLabels }}
{{ toYaml .Values.global.postgresql.extraLabels | indent 4 }}
{{- end }}
type: Opaque
data:
  postgresql-password: {{ include "postgresql.password" . | b64enc | quote }}