apiVersion: v1
kind: Service
metadata:
  name: {{ template "api.fullname" . }}
  labels:
    app: {{ template "api.name" . }}
    chart: {{ template "api.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  ports:
  - port: {{ template "api.port" . }}
  selector:
    app: {{ template "api.name" . }} 
    chart: {{ template "api.chart" . }}
    release: {{ .Release.Name | quote }}